### ISSUE TITLE
Compiling data retrieval service throws an error

### ISSUE THREAD

**Issue by akshaygpt** [airavata-courses/Orenda#53]

**Comment by DishaTalreja3** [comment]
We have updated the wiki page to include the command that solves that issue.

**Comment by akshaygpt** [comment]
Thanks! Able to compile and run now.

**Comment by akshaygpt** [comment]
For documentation, writing the issue experienced here:
While trying to compile the data retrieval
`ERROR: Cannot uninstall docutils`
