### ISSUE TITLE
ModuleNotFoundError - Data Retrieval Service .

### ISSUE THREAD

**Issue by akhil-8607** [airavata-courses/Orenda#54]
Hello Team , I am peer reviewing your project and found the Module not found errors when running the Data Retrieval Service for not finding the module nexradaws . I have attached screenshot below for your reference .

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/16973298/74446838-7d97d080-4e46-11ea-9fff-3dbf72f4d1f9.png">

**Comment by DishaTalreja3** [comment]
Hi Akhil, Did you try executing the following command :
"pip install -r requirements.txt" before executing the python file 'app.py'?

**Comment by akhil-8607** [comment]
I tried it , It's working now
