### ISSUE TITLE
Topic doesn't exist - session Management 

### ISSUE THREAD

**Issue by akhil-8607** [airavata-courses/Orenda#55]
Getting the error ssessionManagementConsumerF topic  does not exist for session management service .

<img width="492" alt="image" src="https://user-images.githubusercontent.com/16973298/74453915-159ab780-4e51-11ea-869e-388fad2aec26.png">

**Comment by milanchheta** [comment]
Docker-compose.yml file was updated to solve this issue

**Comment by akhil-8607** [comment]
it's working now
